development:
  firebase_key: firebase_key
  smtp:
   server: 'smtp.gmail.com'
   domain: 'gmail.com'
   port: 465
   user_name: user_name
   password: password
   starttls: yes
   tls: yes
   from: 'no-reply@mailg.co'