Specialty.find_or_create_by name: "Alergia E Inmunología"
Specialty.find_or_create_by name: "Anatomía Patológica"
Specialty.find_or_create_by name: "Anestesiología"
Specialty.find_or_create_by name: "Angiología General Y Hemodinamia"
Specialty.find_or_create_by name: "Cardiología"
Specialty.find_or_create_by name: "Cardiólogo Infantil"
Specialty.find_or_create_by name: "Cirugía General"
Specialty.find_or_create_by name: "Cirugía Cardiovascular"
Specialty.find_or_create_by name: "Cirugía De Cabeza Y Cuello"
Specialty.find_or_create_by name: "Cirugía De Tórax (Cirugía Torácica)"
Specialty.find_or_create_by name: "Cirugía Infantil (Cirugía Pediátrica)"
Specialty.find_or_create_by name: "Cirugía Plástica Y Reparadora"
Specialty.find_or_create_by name: "Cirugía Vascular Periférica"
Specialty.find_or_create_by name: "Clínica Médica"
Specialty.find_or_create_by name: "Coloproctología"
Specialty.find_or_create_by name: "Dermatología"
Specialty.find_or_create_by name: "Diagnostico Por Imágenes"
Specialty.find_or_create_by name: "Endocrinología"
Specialty.find_or_create_by name: "Endocrinólogo Infantil"
Specialty.find_or_create_by name: "Farmacología Clínica"
Specialty.find_or_create_by name: "Fisiatría (Medicina Física Y Rehabilitación)"
Specialty.find_or_create_by name: "Gastroenterología"
Specialty.find_or_create_by name: "Gastroenterólogo Infantil"
Specialty.find_or_create_by name: "Genética Medica"
Specialty.find_or_create_by name: "Geriatría"
Specialty.find_or_create_by name: "Ginecología"
Specialty.find_or_create_by name: "Hematología"
Specialty.find_or_create_by name: "Hematólogo Infantil"
Specialty.find_or_create_by name: "Hemoterapia E Inmunohematología"
Specialty.find_or_create_by name: "Infectología"
Specialty.find_or_create_by name: "Infectólogo Infantil"
Specialty.find_or_create_by name: "Medicina Del Deporte"
Specialty.find_or_create_by name: "Medicina General Y/O Medicina De Familia"
Specialty.find_or_create_by name: "Medicina Legal"
Specialty.find_or_create_by name: "Medicina Nuclear"
Specialty.find_or_create_by name: "Medicina Del Trabajo"
Specialty.find_or_create_by name: "Nefrología"
Specialty.find_or_create_by name: "Nefrólogo Infantil"
Specialty.find_or_create_by name: "Neonatología"
Specialty.find_or_create_by name: "Neumonología"
Specialty.find_or_create_by name: "Neumonólogo Infantil"
Specialty.find_or_create_by name: "Neurocirugía"
Specialty.find_or_create_by name: "Neurología"
Specialty.find_or_create_by name: "Neurólogo Infantil"
Specialty.find_or_create_by name: "Nutrición"
Specialty.find_or_create_by name: "Obstetricia"
Specialty.find_or_create_by name: "Oftalmología"
Specialty.find_or_create_by name: "Oncología"
Specialty.find_or_create_by name: "Oncólogo Infantil"
Specialty.find_or_create_by name: "Ortopedia Y Traumatología"
Specialty.find_or_create_by name: "Otorrinolaringología"
Specialty.find_or_create_by name: "Pediatría"
Specialty.find_or_create_by name: "Psiquiatría"
Specialty.find_or_create_by name: "Psiquiatría Infanto Juvenil"
Specialty.find_or_create_by name: "Radioterapia O Terapia Radiante"
Specialty.find_or_create_by name: "Reumatología"
Specialty.find_or_create_by name: "Reumatólogo Infantil"
Specialty.find_or_create_by name: "Terapia Intensiva"
Specialty.find_or_create_by name: "Terapista Intensivo Infantil"
Specialty.find_or_create_by name: "Tocoginecología"
Specialty.find_or_create_by name: "Toxicología"
Specialty.find_or_create_by name: "Urología"